version: '3.9'

services:
  src:
    container_name: little_automation_tool
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql

  psql:
    container_name: psql_little_tool
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env

volumes:
  postgres_data:
