# Generated by Django 4.2.25 on 2025-10-13 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_telegram_connected', models.BooleanField(default=False)),
                ('telegram_connected_at', models.DateTimeField(blank=True, null=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='TelegramVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de Verificação Telegram',
                'verbose_name_plural': 'Códigos de Verificação Telegram',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'is_used'], name='server_tele_code_02e3e9_idx'), models.Index(fields=['user', 'is_used'], name='server_tele_user_id_d329ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(blank=True, max_length=255)),
                ('message_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_message_id', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação Telegram',
                'verbose_name_plural': 'Notificações Telegram',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='server_tele_user_id_7b3b05_idx'), models.Index(fields=['status', 'created_at'], name='server_tele_status_002445_idx')],
            },
        ),
    ]
