# Generated by Django 4.2.26 on 2025-11-20 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_notion_connected',
            field=models.BooleanField(default=False, verbose_name='Notion Conectado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notion_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notion_database_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notion Database ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notion_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notion Token'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Matéria')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('professor', models.CharField(blank=True, max_length=200, verbose_name='Professor')),
                ('total_classes', models.IntegerField(default=0, verbose_name='Total de Aulas')),
                ('max_absences', models.IntegerField(default=0, verbose_name='Limite de Faltas')),
                ('current_absences', models.IntegerField(default=0, verbose_name='Faltas Atuais')),
                ('schedule_info', models.JSONField(blank=True, default=dict, verbose_name='Horários')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Cor')),
                ('semester', models.CharField(blank=True, max_length=20, verbose_name='Semestre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notion_page_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matéria',
                'verbose_name_plural': 'Matérias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('pdf_file', models.FileField(upload_to='study_plans/%Y/%m/', verbose_name='Arquivo PDF')),
                ('file_size', models.IntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_raw_response', models.TextField(blank=True, verbose_name='Resposta Bruta da IA')),
                ('ai_analysis', models.JSONField(blank=True, default=dict, verbose_name='Análise Estruturada')),
                ('events_created', models.IntegerField(default=0, verbose_name='Eventos Criados')),
                ('subjects_created', models.IntegerField(default=0, verbose_name='Matérias Criadas')),
                ('synced_to_notion', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de Estudos',
                'verbose_name_plural': 'Planos de Estudos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('event_type', models.CharField(choices=[('prova', '📝 Prova'), ('trabalho', '📄 Trabalho'), ('entrega', '📤 Entrega'), ('revisao', '📖 Revisão'), ('aula', '🎓 Aula'), ('outro', '📚 Outro')], max_length=20, verbose_name='Tipo')),
                ('event_date', models.DateField(verbose_name='Data')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Horário')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Horário Fim')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Local')),
                ('notion_page_id', models.CharField(blank=True, max_length=50, null=True)),
                ('synced_to_notion', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=3, verbose_name='Prioridade')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent_1d', models.BooleanField(default=False, verbose_name='Notif. 1 dia antes')),
                ('notification_sent_3h', models.BooleanField(default=False, verbose_name='Notif. 3h antes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='server.studyplan')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='server.subject')),
            ],
            options={
                'verbose_name': 'Evento de Estudo',
                'verbose_name_plural': 'Eventos de Estudo',
                'ordering': ['event_date', 'event_time'],
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['user', 'is_active'], name='server_subj_user_id_c26f3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('user', 'name', 'semester')},
        ),
        migrations.AddIndex(
            model_name='studyevent',
            index=models.Index(fields=['event_date', 'is_completed'], name='server_stud_event_d_515d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='studyevent',
            index=models.Index(fields=['study_plan', 'event_date'], name='server_stud_study_p_a451e8_idx'),
        ),
    ]
